language: node_js
node_js:
  - "0.10"
notifications:
  irc: "irc.mibbit.net#heartless"
    use_notice: true
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change : %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"